/**
 * office-text.ts — turn a .docx/.xlsx/.pptx attachment into plain text a build turn can read (spec 089).
 *
 * The attachment mechanism injects a PATH and lets the turn `Read` the file, which works for text and
 * PDF but not for Office formats — those are zips of XML. Rather than teach the turn a new trick, the
 * server extracts at upload time and writes a text SIDECAR next to the original; the sidecar's path is
 * what gets injected. The turn stays unchanged.
 *
 * Deliberately lossy. The output exists to be REASONED OVER, not to reconstruct the document: styling,
 * images, and positioning are dropped, and each format loses a little more (see {@link scopeCaveat},
 * which ships inside every sidecar so the model reads the same caveats a human would).
 *
 * All parsing is regex over the part XML — no XML dependency. That is sound here because the inputs are
 * machine-generated by Office itself (no exotic constructs), the element vocabulary consumed is tiny,
 * and the failure mode is a wrong-looking sidecar rather than a security boundary: `unzip.ts` already
 * guarantees nothing reaches the filesystem and nothing inflates without bound.
 */
import { readEntries } from './unzip.js';

/** Extensions this module can extract. */
export const OFFICE_EXT = new Set(['docx', 'xlsx', 'pptx']);
/**
 * The pre-2007 binary formats. They are OLE compound files, NOT zips, so they need an entirely separate
 * parser and are refused outright — but refused BY NAME, because "unsupported file" on a .doc while
 * .docx works is baffling unless the message says to re-save.
 */
export const LEGACY_OFFICE_EXT = new Set(['doc', 'xls', 'ppt']);

const XML_ENTITIES: Record<string, string> = { amp: '&', lt: '<', gt: '>', quot: '"', apos: "'" };

/** Resolve the five predefined XML entities plus numeric character references. */
function decodeXml(s: string): string {
  if (!s.includes('&')) return s;
  return s.replace(/&(#[0-9]+|#[xX][0-9a-fA-F]+|[a-zA-Z]+);/g, (whole, body: string) => {
    if (body[0] === '#') {
      const code = body[1] === 'x' || body[1] === 'X' ? parseInt(body.slice(2), 16) : parseInt(body.slice(1), 10);
      if (!Number.isFinite(code) || code <= 0 || code > 0x10ffff) return whole;
      try {
        return String.fromCodePoint(code);
      } catch {
        return whole; // lone surrogate — leave the reference as written
      }
    }
    return XML_ENTITIES[body.toLowerCase()] ?? whole;
  });
}

/** Read one attribute out of a start-tag string (`<c r="A1" t="s">` → `attr(tag, 'r') === 'A1'`). */
function attr(tag: string, name: string): string | null {
  const m = new RegExp(`(?:^|\\s)${name}="([^"]*)"`).exec(tag);
  return m ? decodeXml(m[1]) : null;
}

/**
 * Concatenate every `<t>` element's text, in order.
 *
 * `<rPh>` runs are stripped first: they hold furigana (phonetic readings) for Japanese text and contain
 * their own `<t>`, so keeping them would interleave カタカナ readings into every kanji cell — a real
 * corruption for this workspace's Japanese source documents, not a hypothetical one.
 */
function tTexts(xml: string): string {
  const cleaned = xml.replace(/<rPh\b[\s\S]*?<\/rPh>/g, '');
  let out = '';
  const re = /<(?:\w+:)?t\b[^>]*>([\s\S]*?)<\/(?:\w+:)?t>/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(cleaned))) out += decodeXml(m[1]);
  return out;
}

/** Resolve an OPC relationship Target against the part directory that owns the .rels file. */
function relTarget(baseDir: string, target: string): string {
  if (target.startsWith('/')) return target.slice(1);
  const parts = baseDir.split('/').filter(Boolean);
  for (const seg of target.split('/')) {
    if (!seg || seg === '.') continue;
    if (seg === '..') parts.pop();
    else parts.push(seg);
  }
  return parts.join('/');
}

/** Map `Id` → resolved entry name for every relationship in a .rels part. */
function relMap(rels: Buffer | undefined, baseDir: string): Map<string, string> {
  const out = new Map<string, string>();
  if (!rels) return out;
  for (const tag of rels.toString('utf8').match(/<Relationship\b[^>]*>/g) ?? []) {
    const id = attr(tag, 'Id');
    const target = attr(tag, 'Target');
    if (id && target) out.set(id, relTarget(baseDir, target));
  }
  return out;
}

/* ---------------------------------------------------------------- .docx */

/**
 * Word body text. Paragraphs become lines; tables become GitHub-flavoured markdown rows so a
 * requirements table survives as a table instead of collapsing into one run-on line.
 *
 * A table nested inside a table cell is not modelled — the flat row/cell state resets, so the inner
 * table's rows land as ordinary rows. That degrades readably and cannot throw, which is the right
 * trade for a construct that effectively does not appear in proposal documents.
 */
function docxText(zip: Map<string, Buffer>): string {
  const part = zip.get('word/document.xml');
  if (!part) throw new Error('missing word/document.xml — not a Word document');
  const src = part.toString('utf8');

  const lines: string[] = [];
  let run: string[] = []; // text runs of the paragraph being built
  let cellPars: string[] | null = null; // paragraphs of the table cell being built
  let cells: string[] | null = null; // finished cells of the table row being built
  let tableCols = 0; // column count of the current table's first row
  let tableAt = -1; // index in `lines` of the current table's first row
  let inT = false;

  const flushPara = (): void => {
    const text = run.join('').replace(/[ \t]+$/, '');
    run = [];
    if (cellPars) cellPars.push(text);
    else lines.push(text);
  };

  const re = /<[^>]*>|[^<]+/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(src))) {
    const tok = m[0];
    if (tok[0] !== '<') {
      if (inT) run.push(decodeXml(tok));
      continue;
    }
    // `<w:t>` and `<w:t xml:space="preserve">` open a text run; `<w:tab/>`/`<w:tbl>`/`<w:tc>`/`<w:tr>`
    // share the prefix, so the delimiter must be part of the match.
    if (tok.startsWith('<w:t>') || tok.startsWith('<w:t ')) inT = !tok.endsWith('/>');
    else if (tok === '</w:t>') inT = false;
    else if (tok.startsWith('<w:tab')) run.push('\t');
    // A hard break inside a cell must not become a newline — that would split the markdown row.
    else if (tok.startsWith('<w:br') || tok.startsWith('<w:cr')) run.push(cellPars ? ' ' : '\n');
    else if (tok === '</w:p>' || tok.startsWith('<w:p/')) flushPara();
    else if (tok.startsWith('<w:tbl>') || tok.startsWith('<w:tbl ')) {
      tableAt = lines.length;
      tableCols = 0;
    } else if (tok.startsWith('<w:tr>') || tok.startsWith('<w:tr ')) cells = [];
    else if (tok.startsWith('<w:tc>') || tok.startsWith('<w:tc ')) cellPars = [];
    else if (tok === '</w:tc>') {
      cells?.push((cellPars ?? []).join(' ').trim());
      cellPars = null;
    } else if (tok === '</w:tr>') {
      if (cells?.length) {
        lines.push(`| ${cells.map((c) => c.replace(/\|/g, '\\|').replace(/\s*\n\s*/g, ' ')).join(' | ')} |`);
        if (!tableCols) tableCols = cells.length;
      }
      cells = null;
    } else if (tok === '</w:tbl>') {
      // A markdown table needs the `| --- |` rule under its header row, or it renders as plain text.
      if (tableCols && tableAt >= 0 && lines.length > tableAt) {
        lines.splice(tableAt + 1, 0, `| ${Array(tableCols).fill('---').join(' | ')} |`);
      }
      lines.push('');
      tableAt = -1;
      tableCols = 0;
    }
  }
  return lines.join('\n').replace(/\n{3,}/g, '\n\n').trim();
}

/* ---------------------------------------------------------------- .pptx */

const SLIDE_ENTRY = /^ppt\/slides\/slide[^/]+\.xml$/;

/**
 * Slide text in PRESENTATION order, which is read from `<p:sldIdLst>` + the presentation relationships —
 * not from the file names. PowerPoint keeps a slide's original part name when the deck is reordered, so
 * `slide3.xml` is routinely the first slide; sorting by the trailing number silently scrambles the deck.
 * Numeric order is only the fallback for a deck whose presentation part is unreadable.
 */
function pptxText(zip: Map<string, Buffer>): string {
  const pres = zip.get('ppt/presentation.xml');
  const rels = relMap(zip.get('ppt/_rels/presentation.xml.rels'), 'ppt');

  let order: string[] = [];
  if (pres && rels.size) {
    for (const tag of pres.toString('utf8').match(/<p:sldId\b[^>]*>/g) ?? []) {
      const id = attr(tag, 'r:id');
      const entry = id ? rels.get(id) : null;
      if (entry && zip.has(entry)) order.push(entry);
    }
  }
  if (!order.length) {
    order = [...zip.keys()]
      .filter((n) => SLIDE_ENTRY.test(n))
      .sort((a, b) => (parseInt(a.replace(/\D+/g, ''), 10) || 0) - (parseInt(b.replace(/\D+/g, ''), 10) || 0));
  }
  if (!order.length) throw new Error('no slides found — not a PowerPoint presentation');

  const out: string[] = [];
  order.forEach((entry, i) => {
    const src = zip.get(entry)?.toString('utf8') ?? '';
    const body = src
      .split('</a:p>')
      .map((para) => tTexts(para).trim())
      .filter(Boolean);
    out.push(`## Slide ${i + 1}`, ...body, '');
  });
  return out.join('\n').replace(/\n{3,}/g, '\n\n').trim();
}

/* ---------------------------------------------------------------- .xlsx */

const SHEET_ENTRY = /^xl\/worksheets\/[^/]+\.xml$/;

/** `"B3"` → 1. Returns -1 when the reference has no column letters. */
function colIndex(ref: string): number {
  let n = 0;
  for (const ch of ref) {
    const c = ch.toUpperCase();
    if (c < 'A' || c > 'Z') break;
    n = n * 26 + (c.charCodeAt(0) - 64);
  }
  return n - 1;
}

const csvCell = (s: string): string => (/[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s);

/**
 * Every sheet as CSV under its own `## <sheet name>` heading.
 *
 * The load-bearing detail is that an empty cell is OMITTED from the XML rather than written as blank,
 * so each cell must be placed by parsing its `r="B3"` reference. Reading cells sequentially shifts every
 * value left of a gap into the wrong column — the single most likely way for this extractor to produce
 * confident, wrong data.
 *
 * Values are raw: a date arrives as its serial number, and a formula yields its cached result. Rows that
 * are entirely empty are dropped (style-only rows otherwise pad the output with thousands of commas).
 */
function xlsxText(zip: Map<string, Buffer>): string {
  const shared: string[] = [];
  const ss = zip.get('xl/sharedStrings.xml');
  if (ss) {
    for (const chunk of ss.toString('utf8').split('</si>')) {
      if (chunk.includes('<si')) shared.push(tTexts(chunk));
    }
  }

  const rels = relMap(zip.get('xl/_rels/workbook.xml.rels'), 'xl');
  const sheets: { name: string; entry: string }[] = [];
  const wb = zip.get('xl/workbook.xml');
  if (wb) {
    for (const tag of wb.toString('utf8').match(/<sheet\b[^>]*>/g) ?? []) {
      const id = attr(tag, 'r:id');
      const entry = id ? rels.get(id) : null;
      if (entry && zip.has(entry)) sheets.push({ name: attr(tag, 'name') ?? entry, entry });
    }
  }
  if (!sheets.length) {
    for (const entry of [...zip.keys()].filter((n) => SHEET_ENTRY.test(n)).sort()) {
      sheets.push({ name: entry.split('/').pop() ?? entry, entry });
    }
  }
  if (!sheets.length) throw new Error('no worksheets found — not an Excel workbook');

  const out: string[] = [];
  for (const sheet of sheets) {
    const src = zip.get(sheet.entry)?.toString('utf8') ?? '';
    const rows: string[][] = [];
    let width = 0;

    for (const rowXml of src.split('</row>')) {
      if (!rowXml.includes('<row')) continue;
      const cellsOut: string[] = [];
      let auto = 0; // fallback position for a cell with no `r` reference
      const re = /<c\b([^>]*?)(?:\/>|>([\s\S]*?)<\/c>)/g;
      let m: RegExpExecArray | null;
      while ((m = re.exec(rowXml))) {
        const tag = m[1] ?? '';
        const inner = m[2] ?? '';
        const ref = attr(`<c${tag}>`, 'r');
        const at = ref ? colIndex(ref) : -1;
        const col = at >= 0 ? at : auto;
        auto = col + 1;

        const type = attr(`<c${tag}>`, 't') ?? 'n';
        const v = /<v\b[^>]*>([\s\S]*?)<\/v>/.exec(inner);
        const raw = v ? decodeXml(v[1]) : '';
        let value: string;
        if (type === 's') value = shared[Number(raw)] ?? '';
        else if (type === 'inlineStr') value = tTexts(inner);
        else if (type === 'b') value = raw === '1' ? 'TRUE' : raw === '0' ? 'FALSE' : raw;
        else value = raw;

        while (cellsOut.length < col) cellsOut.push('');
        cellsOut[col] = value;
      }
      if (cellsOut.some((c) => c !== '')) {
        rows.push(cellsOut);
        width = Math.max(width, cellsOut.length);
      }
    }

    out.push(`## ${sheet.name}`);
    if (!rows.length) out.push('(empty sheet)');
    else {
      for (const row of rows) {
        while (row.length < width) row.push('');
        out.push(row.map(csvCell).join(','));
      }
    }
    out.push('');
  }
  return out.join('\n').replace(/\n{3,}/g, '\n\n').trim();
}

/* ---------------------------------------------------------------- public */

/** Human label + the honest limits of what was extracted, for the sidecar header. */
function scopeCaveat(ext: string): { label: string; scope: string } {
  switch (ext) {
    case 'docx':
      return {
        label: 'Word document',
        scope:
          'document body only — text boxes, headers/footers, comments and tracked changes are not ' +
          'included, and list numbering is dropped (the order of items is preserved)',
      };
    case 'xlsx':
      return {
        label: 'Excel workbook',
        scope:
          'cell values as CSV per sheet — values are raw, so dates appear as Excel serial numbers and ' +
          'formulas appear as their cached results; formatting and charts are not included',
      };
    default:
      return { label: 'PowerPoint presentation', scope: 'text on slides only — speaker notes, images and diagrams are not included' };
  }
}

/** Which zip parts each format needs. Everything else in the archive is skipped, never inflated. */
function wanted(ext: string): (name: string) => boolean {
  if (ext === 'docx') return (n) => n === 'word/document.xml';
  if (ext === 'pptx') {
    return (n) => n === 'ppt/presentation.xml' || n === 'ppt/_rels/presentation.xml.rels' || SLIDE_ENTRY.test(n);
  }
  return (n) =>
    n === 'xl/workbook.xml' || n === 'xl/_rels/workbook.xml.rels' || n === 'xl/sharedStrings.xml' || SHEET_ENTRY.test(n);
}

/**
 * Extract plain text from an Office file's bytes. Returns trimmed text — possibly EMPTY, which callers
 * must treat as a failure rather than write out: a document that yields no text (scanned images only, a
 * blank workbook) would otherwise reach the model as a file that exists and says nothing.
 *
 * Throws with a user-facing message when the bytes are not a readable file of that type.
 */
export function extractOfficeText(ext: string, bytes: Buffer): string {
  if (!OFFICE_EXT.has(ext)) throw new Error(`no text extractor for '${ext}'`);
  const zip = readEntries(bytes, wanted(ext));
  if (ext === 'docx') return docxText(zip);
  if (ext === 'pptx') return pptxText(zip);
  return xlsxText(zip);
}

/**
 * Assemble the sidecar file: a short provenance header followed by the extracted text, truncated to
 * `maxChars` if needed.
 *
 * The header is not decoration. A `.md` sidecar cannot say what it used to be, and every caveat about
 * what extraction dropped only helps if the MODEL reads it — the sidecar is the one place it certainly
 * will. The truncation notice goes in the header rather than at the end of the file for the obvious
 * reason that the end is what truncation removes.
 */
export function sidecarText(ext: string, originalName: string, body: string, maxChars: number): string {
  const { label, scope } = scopeCaveat(ext);
  const kept = body.length > maxChars ? body.slice(0, maxChars) : body;
  const head = [
    `> Extracted from **${originalName}** (${label}) — machine-extracted plain text, not the original file.`,
    `> Scope: ${scope}.`,
  ];
  if (kept.length < body.length) {
    head.push(`> TRUNCATED: showing the first ${kept.length} of ${body.length} characters.`);
  }
  return `${head.join('\n')}\n\n${kept}\n`;
}
