#!/usr/bin/env python3
"""Build searchable index of all Dify workflow YAMLs in the base workspace.

Scans templates/, corpus/, skill assets, and any project workflows.
Outputs:
  - tools/dify_base/index.json (machine-readable)
  - INDEX.md (human-readable, sorted by source + complexity)

Usage:
    python3 tools/dify_base/build_index.py
"""
import json
import subprocess
import yaml
from pathlib import Path
from collections import Counter
from urllib.parse import quote

# dify-projects/tools/dify_base/build_index.py -> parent.parent.parent = base root
BASE = Path(__file__).parent.parent.parent


def _md_link_target(abs_path):
    """Turn an absolute path into a repo-relative, URL-safe Markdown link target.

    Parentheses, spaces, and CJK chars in filenames can break Markdown links;
    quote() keeps '/' as-is so the relative structure stays readable.
    """
    rel = Path(abs_path).resolve().relative_to(BASE.resolve())
    return quote(str(rel), safe='/')

SCAN_PATHS = [
    (BASE / "templates" / "patterns", "patterns"),
    (BASE / "templates" / "_base", "starter"),
    (BASE / "examples", "example"),
    (BASE / "corpus" / "awesome-dify-workflow" / "DSL", "corpus"),
    (BASE / "skills" / "mango-svip" / "assets", "skill-assets"),
    (BASE / "skills" / "Tomatio13" / "example", "skill-assets"),
    (BASE / "projects", "project"),
]

INTERESTING_NODE_TYPES = [
    "iteration", "loop", "code", "llm", "http-request", "tool",
    "if-else", "document-extractor", "knowledge-retrieval", "agent",
    "template-transform", "variable-aggregator", "variable-assigner",
    "assigner", "parameter-extractor", "question-classifier",
    "list-operator", "answer",
]


def analyze(yaml_path):
    try:
        with open(yaml_path, encoding='utf-8') as f:
            data = yaml.safe_load(f)
    except Exception:
        return None

    if not isinstance(data, dict):
        return None

    app = data.get('app') or {}
    workflow = data.get('workflow') or {}
    graph = workflow.get('graph') or {}
    nodes = graph.get('nodes') or []

    node_types = []
    has_file_input = False
    for n in nodes:
        d = n.get('data') or {}
        ntype = d.get('type') or ''
        if not ntype or ntype in ('iteration-start', 'loop-start', 'custom-iteration-start', 'custom-loop-start'):
            continue
        node_types.append(ntype)
        if ntype == 'start':
            for v in (d.get('variables') or []):
                if v.get('type') in ('file', 'file-list'):
                    has_file_input = True

    type_counter = Counter(node_types)
    unique_types = sorted(type_counter.keys())

    plugins = []
    for dep in (data.get('dependencies') or []):
        if isinstance(dep, dict):
            pid = (dep.get('value') or {}).get('marketplace_plugin_unique_identifier', '')
            if pid:
                name = pid.split(':')[0]
                plugins.append(name)

    node_count = len(node_types)
    has_iter = 'iteration' in type_counter or 'loop' in type_counter
    if node_count <= 4 and not has_iter:
        complexity = "Simple"
    elif node_count >= 10 or (has_iter and node_count >= 7):
        complexity = "Complex"
    else:
        complexity = "Medium"

    info = {
        "file": yaml_path.name,
        "path": str(yaml_path),
        "name": app.get('name', '') or '',
        "description": ((app.get('description') or '').strip())[:100],
        "mode": app.get('mode', '') or '',
        "version": str(data.get('version', '') or ''),
        "node_count": node_count,
        "node_types": unique_types,
        "complexity": complexity,
        "has_file_input": has_file_input,
        "plugins": plugins,
    }
    for t in INTERESTING_NODE_TYPES:
        info[f"has_{t.replace('-', '_')}"] = (t in type_counter)
    return info


def write_markdown(entries, out_path):
    lines = [
        "# Dify Base — Template Index",
        "",
        f"Auto-generated by [`tools/dify_base/build_index.py`](tools/dify_base/build_index.py). **{len(entries)} files indexed.**",
        "",
        "**Tip**: Use `tools/dify_base/find.py --has <feature>` for quick CLI search. See [docs/GUIDE.md](docs/GUIDE.md) for full guide.",
        "",
        "## Main Table",
        "",
        "Sorted by source, then complexity.",
        "",
        "| Source | File | Nodes | Complexity | Key Features | Plugins | Description |",
        "|---|---|---|---|---|---|---|",
    ]

    order = {"Simple": 0, "Medium": 1, "Complex": 2}
    sorted_entries = sorted(entries, key=lambda x: (x['source'], order.get(x['complexity'], 9), x['file']))

    for e in sorted_entries:
        features = []
        if e['has_iteration']: features.append('iteration')
        if e['has_loop']: features.append('loop')
        if e['has_file_input']: features.append('file-in')
        if e['has_http_request']: features.append('http')
        if e['has_code']: features.append('code')
        if e['has_llm']: features.append('llm')
        if e['has_if_else']: features.append('if-else')
        if e['has_tool']: features.append('tool')
        if e['has_document_extractor']: features.append('doc-extract')
        if e['has_knowledge_retrieval']: features.append('rag')
        if e['has_agent']: features.append('agent')
        if e['has_parameter_extractor']: features.append('param-extract')
        if e['has_template_transform']: features.append('jinja')
        features_str = ', '.join(features) if features else '-'

        plugins_str = ', '.join(p.split('/')[-1] for p in e['plugins'][:2]) if e['plugins'] else '-'
        if len(e['plugins']) > 2:
            plugins_str += f' (+{len(e["plugins"])-2})'

        desc = (e['description'] or e['name'] or '-').replace('|', '\\|').replace('\n', ' ')[:50]

        file_display = e['file'].replace('|', '\\|')
        file_link = f"[{file_display}]({_md_link_target(e['path'])})"

        lines.append(
            f"| `{e['source']}` | {file_link} | {e['node_count']} | {e['complexity']} | {features_str} | {plugins_str} | {desc} |"
        )

    lines.extend(["", "## By Feature", ""])

    feature_groups = {
        "Iteration / Loop (bulk processing)": ["has_iteration", "has_loop"],
        "File Input (upload)": ["has_file_input"],
        "Document Extractor (parse file)": ["has_document_extractor"],
        "HTTP Request (call external API)": ["has_http_request"],
        "Code Node (Python/JS)": ["has_code"],
        "LLM Node": ["has_llm"],
        "If-Else (branching)": ["has_if_else"],
        "Tool (call plugin)": ["has_tool"],
        "Knowledge Retrieval (RAG)": ["has_knowledge_retrieval"],
        "Agent": ["has_agent"],
        "Parameter Extractor": ["has_parameter_extractor"],
        "Template Transform (Jinja2)": ["has_template_transform"],
    }

    for label, keys in feature_groups.items():
        matches = [e for e in entries if any(e.get(k) for k in keys)]
        if not matches:
            continue
        lines.append(f"### {label} — {len(matches)} files")
        lines.append("")
        for e in sorted(matches, key=lambda x: (order.get(x['complexity'], 9), x['file'])):
            lines.append(f"- `{e['source']}` / [{e['file']}]({_md_link_target(e['path'])}) — {e['complexity']}, {e['node_count']} nodes")
        lines.append("")

    lines.extend(["## By Complexity", ""])
    for level in ["Simple", "Medium", "Complex"]:
        matches = [e for e in entries if e['complexity'] == level]
        if not matches:
            continue
        lines.append(f"### {level} — {len(matches)} files")
        lines.append("")
        for e in sorted(matches, key=lambda x: x['file']):
            lines.append(f"- `{e['source']}` / [{e['file']}]({_md_link_target(e['path'])}) — {e['node_count']} nodes")
        lines.append("")

    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))


def _filter_gitignored(paths):
    """Drop paths git would ignore, so the index mirrors the repo rather than local scratch.

    The builder writes each QA run to projects/<slug>/ (gitignored — spec 011 R2); without this,
    rglob would scan those throwaways and leak them into the tracked INDEX.md. Safe fallback: if git
    is unavailable (or errors), keep all paths — the index is never worse than today.
    """
    if not paths:
        return paths
    try:
        proc = subprocess.run(
            ["git", "-C", str(BASE), "check-ignore", "--stdin"],
            input="\n".join(str(p) for p in paths),
            capture_output=True, text=True,
        )
    except Exception:
        return paths
    if proc.returncode not in (0, 1):  # 0 = some ignored, 1 = none ignored, >1 = error
        return paths
    ignored = {line.strip() for line in proc.stdout.splitlines() if line.strip()}
    return [p for p in paths if str(p) not in ignored]


def main():
    all_entries = []
    skipped = []
    for scan_dir, source_tag in SCAN_PATHS:
        if not scan_dir.exists():
            continue
        # Recursive scan to catch YAMLs in subdirs (e.g., corpus/.../图文知识库/), minus gitignored scratch.
        for yml in _filter_gitignored(sorted(scan_dir.rglob("*.yml"))):
            info = analyze(yml)
            if info:
                info['source'] = source_tag
                all_entries.append(info)
            else:
                skipped.append(str(yml))

    out_json = BASE / "tools" / "dify_base" / "index.json"
    out_json.parent.mkdir(parents=True, exist_ok=True)
    with open(out_json, 'w', encoding='utf-8') as f:
        json.dump(all_entries, f, ensure_ascii=False, indent=2)
    print(f"✓ Wrote {out_json.relative_to(BASE)} ({len(all_entries)} entries)")

    out_md = BASE / "INDEX.md"
    write_markdown(all_entries, out_md)
    print(f"✓ Wrote {out_md.relative_to(BASE)}")

    if skipped:
        print(f"  ({len(skipped)} files skipped due to parse errors)")


if __name__ == "__main__":
    main()
