#!/usr/bin/env python3
"""Staleness + license checker for promoted templates (spec 022 D6/D7).

For each template carrying an x-provenance header (default: templates/library/), classify:
  current | stale | orphan
by comparing the recorded orig_sha256 to the LOCAL upstream clone file — no git history, no
network (works against the shallow + blobless intake clones). Also validates license hygiene:
every promoted template must name a permissive license matching its registered source.

Usage:
  python3 tools/dify_base/check_provenance.py                  # table, warn-only (exit 0)
  python3 tools/dify_base/check_provenance.py --strict         # exit 1 on stale/orphan/license issue
  python3 tools/dify_base/check_provenance.py --write-third-party  # (re)generate THIRD_PARTY.md
"""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from sources import load_sources, PERMISSIVE_LICENSES  # noqa: E402
import provenance  # noqa: E402

BASE = Path(__file__).parent.parent.parent
LIBRARY = BASE / "templates" / "library"
THIRD_PARTY = BASE / "THIRD_PARTY.md"


def _rel(p):
    """Repo-relative path for display; falls back to the raw path (e.g. a tmp --dir in tests)."""
    try:
        return Path(p).relative_to(BASE)
    except ValueError:
        return Path(p)


def classify(fields, sources_by_name):
    """Return (status, detail) for one template's provenance fields."""
    src = fields.get("source")
    if src == "original":
        return ("current", "hand-authored (no upstream)")
    s = sources_by_name.get(src)
    if s is None:
        return ("orphan", f"source {src!r} not in registry")
    orig = BASE / "corpus" / src / fields.get("file", "")
    if not orig.exists():
        return ("orphan", f"upstream file missing: corpus/{src}/{fields.get('file')}")
    if not fields.get("orig_sha256"):
        return ("stale", "no orig_sha256 recorded — re-promote to stamp it")
    if provenance.sha256_file(orig) == fields["orig_sha256"]:
        return ("current", "matches upstream")
    return ("stale", "upstream file changed since promotion")


def license_problems(fields, sources_by_name):
    """Return a list of license-hygiene problems (empty = clean)."""
    probs = []
    src = fields.get("source")
    lic = fields.get("license")
    if not lic:
        probs.append("missing license")
    elif lic not in PERMISSIVE_LICENSES:
        probs.append(f"non-permissive license {lic!r}")
    if src and src != "original":
        s = sources_by_name.get(src)
        if s and lic and s.get("license") and lic != s["license"]:
            probs.append(f"license {lic!r} != registry {s['license']!r}")
    return probs


def find_templates(root):
    return [p for p in sorted(root.rglob("*.yml")) if provenance.parse_header(p)]


def write_third_party(records, sources_by_name):
    """Aggregate attributions for redistribution into THIRD_PARTY.md."""
    by_source = {}
    for rel, fields in records:
        src = fields.get("source")
        if src == "original":
            continue
        by_source.setdefault(src, []).append((rel, fields))
    lines = [
        "# Third-party attributions",
        "",
        "Templates in [`templates/library/`](templates/library/) are **derived works** (migrated to the",
        "current DSL, lightly edited to house style) promoted from the vendored sources in",
        "[`corpus/sources.yml`](corpus/sources.yml). Each retains its upstream license; this file",
        "aggregates attribution for redistribution. Auto-generated by `tools/dify_base/check_provenance.py`.",
        "",
    ]
    if not by_source:
        lines.append("_No promoted templates yet._")
    for src in sorted(by_source):
        s = sources_by_name.get(src, {})
        lines.append(f"## {src} — {s.get('license', '?')}")
        lines.append("")
        if s.get("repo"):
            lines.append(f"Source: {s['repo']}")
            lines.append("")
        for rel, f in sorted(by_source[src]):
            lines.append(f"- `{rel}` ← `{f.get('file','?')}` (commit `{f.get('commit','?')}`)")
        lines.append("")
    THIRD_PARTY.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"✓ Wrote {THIRD_PARTY.relative_to(BASE)} ({len(by_source)} source(s))")


def main(argv=None):
    ap = argparse.ArgumentParser(description="Check promoted-template provenance + license (spec 022)")
    ap.add_argument("--strict", action="store_true", help="exit non-zero on stale/orphan/license issues")
    ap.add_argument("--dir", default=str(LIBRARY), help="curated dir to scan (default: templates/library)")
    ap.add_argument("--write-third-party", action="store_true", help="(re)generate THIRD_PARTY.md")
    args = ap.parse_args(argv)

    sources_by_name = {s["name"]: s for s in load_sources()}
    root = Path(args.dir)
    templates = find_templates(root) if root.exists() else []

    records = []
    bad = False
    print(f"Provenance check — {len(templates)} promoted template(s) in {_rel(root)}:\n")
    for t in templates:
        f = provenance.parse_header(t)
        rel = _rel(t)
        records.append((rel, f))
        status, detail = classify(f, sources_by_name)
        lp = license_problems(f, sources_by_name)
        mark = {"current": "✓", "stale": "•", "orphan": "✗"}.get(status, "?")
        print(f"  {mark} [{status:7}] {rel}  ← {f.get('source')} ({f.get('license')}) — {detail}")
        for p in lp:
            print(f"      ⚠ license: {p}")
        if status in ("stale", "orphan") or lp:
            bad = True
    if not templates:
        print("  (none)")

    if args.write_third_party:
        write_third_party(records, sources_by_name)

    if args.strict and bad:
        print("\n✗ strict mode: provenance/license problems found")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
